// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nawel.Api.Data;

#nullable disable

namespace Nawel.Api.Migrations
{
    [DbContext(typeof(NawelDbContext))]
    partial class NawelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Nawel.Api.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("family", (string)null);
                });

            modelBuilder.Entity("Nawel.Api.Models.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER")
                        .HasColumnName("available");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<bool>("IsGroupGift")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_group_gift");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("list_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("TakenBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taken_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("TakenBy");

                    b.HasIndex("Year");

                    b.ToTable("gifts", (string)null);
                });

            modelBuilder.Entity("Nawel.Api.Models.GiftList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("Nawel.Api.Models.GiftParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GiftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gift_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GiftId", "UserId");

                    b.ToTable("gift_participation", (string)null);
                });

            modelBuilder.Entity("Nawel.Api.Models.OpenGraphRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("opengraph_request", (string)null);
                });

            modelBuilder.Entity("Nawel.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("DisplayPopup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_popup");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("family_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsChildren")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isChildren");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<bool>("NotifyGiftTaken")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notify_gift_taken");

                    b.Property<bool>("NotifyListEdit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notify_list_edit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd");

                    b.Property<string>("Pseudo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("pseudo");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("TEXT")
                        .HasColumnName("token_expiry");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FamilyId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Nawel.Api.Models.Gift", b =>
                {
                    b.HasOne("Nawel.Api.Models.GiftList", "List")
                        .WithMany("Gifts")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nawel.Api.Models.User", "TakenByUser")
                        .WithMany("TakenGifts")
                        .HasForeignKey("TakenBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("List");

                    b.Navigation("TakenByUser");
                });

            modelBuilder.Entity("Nawel.Api.Models.GiftList", b =>
                {
                    b.HasOne("Nawel.Api.Models.User", "User")
                        .WithOne("List")
                        .HasForeignKey("Nawel.Api.Models.GiftList", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nawel.Api.Models.GiftParticipation", b =>
                {
                    b.HasOne("Nawel.Api.Models.Gift", "Gift")
                        .WithMany("Participations")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nawel.Api.Models.User", "User")
                        .WithMany("GiftParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nawel.Api.Models.OpenGraphRequest", b =>
                {
                    b.HasOne("Nawel.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nawel.Api.Models.User", b =>
                {
                    b.HasOne("Nawel.Api.Models.Family", "Family")
                        .WithMany("Users")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Nawel.Api.Models.Family", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Nawel.Api.Models.Gift", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Nawel.Api.Models.GiftList", b =>
                {
                    b.Navigation("Gifts");
                });

            modelBuilder.Entity("Nawel.Api.Models.User", b =>
                {
                    b.Navigation("GiftParticipations");

                    b.Navigation("List");

                    b.Navigation("TakenGifts");
                });
#pragma warning restore 612, 618
        }
    }
}
